name: ts
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cryptography=42.0.5=py312hdda0065_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.6.39=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hfdd30dd_2
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.8.4=py312h06a4308_0
  - matplotlib-base=3.8.4=py312h526ad5a_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - mpmath=1.3.0=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py312h06a4308_0
  - numexpr=2.8.7=py312hf827012_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_1
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.3.0=py312h5eee18b_0
  - pip=24.0=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.0.9=py312h06a4308_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.4=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - qt-main=5.15.2=h53bd1ea_10
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py312h06a4308_0
  - scikit-learn=1.4.2=py312h526ad5a_1
  - scipy=1.13.1=py312hc5e2394_0
  - setuptools=69.5.1=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py312h5eee18b_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.2=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - axial-positional-embedding==0.2.1
      - blinker==1.8.2
      - click==8.1.7
      - colt5-attention==0.11.1
      - comm==0.2.2
      - dash==2.18.0
      - dash-bootstrap-components==1.6.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - einops==0.8.0
      - executing==2.1.0
      - fastavro==1.9.7
      - flask==3.0.3
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - importlib-metadata==8.4.0
      - ipykernel==6.29.5
      - ipython==8.30.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - keras==3.7.0
      - libclang==18.1.1
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - linear-attention-transformer==0.19.1
      - linformer==0.2.3
      - local-attention==1.9.15
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - msgpack==1.0.8
      - multidict==6.4.4
      - namex==0.0.8
      - nest-asyncio==1.6.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - optree==0.13.1
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plotly==5.24.0
      - product-key-memory==0.2.11
      - prompt-toolkit==3.0.48
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.18.0
      - pynvml==11.5.3
      - pytorch-lightning==1.9.5
      - pytorch-warmup==0.2.0
      - pyzmq==26.2.0
      - ray==2.35.0
      - referencing==0.35.1
      - reformer-pytorch==1.4.4
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.20.0
      - scikit-base==0.9.0
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - sktime==0.33.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - swankit==0.2.4
      - swanlab==0.6.4
      - sympy==1.14.0
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io==0.37.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchmetrics==1.7.2
      - torchvision==0.23.0
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - wandb==0.20.1
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - wrapt==1.17.0
      - yarl==1.20.1
      - zipp==3.20.1
prefix: /home/lyh/.conda/envs/ts
